name: "Node VPS Deployment"
description: "Deploy a Node application to a VPS with SSH and PM2 installed and running"
branding:
  icon: "arrow-up-circle"
  color: "purple"

inputs:
  remote-path:
    description: "Remote path where the files are going to be copied"
    required: true
  host:
    description: "Remote host"
    required: true
  username:
    description: "Username to login"
    required: true
  port:
    description: "SSH port"
    required: true
    default: "22"
  password:
    description: "SSH password"
    required: true
  automatic-pre-deploy:
    description: "Deploy automatically"
    required: true
    default: true
  yarn:
    description: "Do you want to use yarn?"
    required: true
    default: false
  build:
    description: "Do you want to build your typescript code?"
    required: true
  pm2-id:
      description: "PM2 ID or Name of the process"
      required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Copy repository contents
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PORT: ${{ inputs.port }}
        PASSWORD: ${{ inputs.password }}
      with:
        source: "."
        target: ${{ inputs.remote-path }}
        
    - name: Run npm clean-install
      if: ${{ inputs.automatic-pre-deploy == true && inputs.yarn == false }}
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PORT: ${{ inputs.port }}
        PASSWORD: ${{ inputs.password }}
        script: cd ${{ inputs.remote-path }} && npm ci
        
    - name: Run yarn install
      if: ${{ inputs.automatic-pre-deploy == true && inputs.yarn == true }}
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PORT: ${{ inputs.port }}
        PASSWORD: ${{ inputs.password }}
        script: cd ${{ inputs.remote-path }} && yarn install
      
    - name: Build your project
      # if: ${{ inputs.build == true }}
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PORT: ${{ inputs.port }}
        PASSWORD: ${{ inputs.password }}
        command: cd ${{ inputs.remote-path }} && echo "fff" >> a
        
    - name: Restart remote application
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PORT: ${{ inputs.port }}
        PASSWORD: ${{ inputs.password }}
        script: pm2 restart ${{ inputs.pm2-id }}